export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const DOWNLOAD_EMPLOYEES = "DOWNLOAD_EMPLOYEES";
export const DOWNLOAD_EMPLOYEES_SUCCESS = "DOWNLOAD_EMPLOYEES_SUCCESS";
export const DOWNLOAD_EMPLOYEES_FAIL = "DOWNLOAD_EMPLOYEES_FAIL";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
